### ISSUE TITLE
Not Support godog v0.12.0 and messages-go/v16 v16.0.1

### ISSUE THREAD

**Issue by YingML** [OpenTagOS/allure2-godog#1]
When I run allure2-godog with godog v0.12.0 and messages-go/v16, the following error occurs：

> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:46:3: cannot use f (type *allureFmt) as type "github.com/cucumber/godog/formatters".Formatter in return argument:
> 	*allureFmt does not implement "github.com/cucumber/godog/formatters".Formatter (wrong type for Feature method)
> 		have Feature(*"github.com/cucumber/messages-go/v10".GherkinDocument, string, []byte)
> 		want Feature(*"github.com/cucumber/messages-go/v16".GherkinDocument, string, []byte)
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:69:44: cannot use scenario.Tags (type []*"github.com/cucumber/messages-go/v16".PickleTag) as type []*"github.com/cucumber/messages-go/v10".Pickle_PickleTag in argument to f.tagsToLabels
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:77:46: cannot use step.Argument (type *"github.com/cucumber/messages-go/v16".PickleStepArgument) as type *"github.com/cucumber/messages-go/v10".PickleStepArgument in argument to stepArgumentToParam
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:104:15: cannot use scenario (type *"github.com/cucumber/messages-go/v16".Pickle) as type *"github.com/cucumber/messages-go/v10".Pickle in argument to isLastStep
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:104:15: cannot use step (type *"github.com/cucumber/messages-go/v16".PickleStep) as type *"github.com/cucumber/messages-go/v10".Pickle_PickleStep in argument to isLastStep
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:136:15: cannot use scenario (type *"github.com/cucumber/messages-go/v16".Pickle) as type *"github.com/cucumber/messages-go/v10".Pickle in argument to isLastStep
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:136:15: cannot use step (type *"github.com/cucumber/messages-go/v16".PickleStep) as type *"github.com/cucumber/messages-go/v10".Pickle_PickleStep in argument to isLastStep
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:149:15: cannot use scenario (type *"github.com/cucumber/messages-go/v16".Pickle) as type *"github.com/cucumber/messages-go/v10".Pickle in argument to isLastStep
> vendor\github.com\OpenTagOS\allure2-godog\alluregodog\allure_formatter.go:149:15: cannot use step (type *"github.com/cucumber/messages-go/v16".PickleStep) as type *"github.com/cucumber/messages-go/v10".Pickle_PickleStep in argument to isLastStep

**Comment by voodoo-dn** [comment]
Hi, @YingML. We've already updated messages-go to version 16. You can use version 0.0.1 of our lib.
